# Generated by Django 3.2.7 on 2021-10-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleWp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField(default=1, null=True)),
                ('destination', models.IntegerField(default=1, null=True)),
            ],
        ),
    ]
