# Generated by Django 3.2.7 on 2021-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleWp',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('post_author', models.IntegerField(null=True)),
                ('post_date', models.DateTimeField(null=True)),
                ('post_date_gmt', models.DateTimeField(null=True)),
                ('post_content', models.TextField(null=True)),
                ('post_title', models.TextField(null=True)),
                ('post_excerpt', models.TextField(null=True)),
                ('post_status', models.TextField(null=True)),
                ('comment_status', models.TextField(null=True)),
                ('ping_status', models.TextField(null=True)),
                ('post_password', models.TextField(null=True)),
                ('post_name', models.TextField(null=True)),
                ('to_ping', models.TextField(null=True)),
                ('pinged', models.TextField(null=True)),
                ('post_modified', models.DateTimeField(null=True)),
                ('post_modified_gmt', models.DateTimeField(null=True)),
                ('post_content_filtered', models.TextField(null=True)),
                ('post_parent', models.IntegerField(null=True)),
                ('guid', models.TextField(null=True)),
                ('menu_order', models.IntegerField(null=True)),
                ('post_type', models.TextField(null=True)),
                ('post_mime_type', models.TextField(null=True)),
                ('comment_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='edition_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='heading',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='hide_from_cover',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_new',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_visible',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='lead',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='section_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='signature',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
